<def f='include/c++/12.2.0/exception' l='56' type='void std::bad_exception::bad_exception()'/>
